### ISSUE TITLE
Error setting up entry 127.0.0.1 for eufy_security

### ISSUE THREAD

**Issue by danymexi** [bropat/hassio-eufy-security-ws#13]
### Add-on version

1.5.2

### Architecture

aarch64

### HomeAssistant version

2023.6.1

### Operating System type

Linux

### Operating system version

11

### Describe the bug

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/product.py:48
Integration: Eufy Security (documentation, issues)
First occurred: 12:03:54 (4 occurrences)
Last logged: 12:55:52

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 106, in _set_products
    self._devices = await self._get_products(ProductType.device, result[MessageField.STATE.value]["devices"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 126, in _get_products
    product = Device(self, serial_no, properties, metadata, commands)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 164, in __init__
    super().__init__(
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 41, in __init__
    self._set_properties(properties)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 48, in _set_properties
    self.name = properties[MessageField.NAME.value]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'name'


It always worked... since 2 days the custom components it's not working anymore... Any clue how to solve?

### To reproduce

1. Go to '...'
2. Click on '...'
3. Scroll down to '....'
4. See error


### Screenshots & Logfiles

_No response_

### Additional context

_No response_

**Comment by Kaspermaat** [comment]
Same over here

**Comment by danymexi** [comment]
Ciao bropat,

Can you please give me quick support to understand what is wrong?

I followed step by step the installation guide... I don't understand, What is the wrong repo you are talking about?  

Thanks a lot!
