### ISSUE TITLE
[Bug]: "Failed to set up" under 2023.6.x

### ISSUE THREAD

**Issue by dlasher** [bropat/hassio-eufy-security-ws#14]
### Add-on version

6.3.0

### Architecture

amd64

### HomeAssistant version

2023.6.1

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

**HA: 2023.6.1 Supervised Debian 11**

used to work, stopped with 2023.6 install, have removed, re-installed, always stalls out.

### To reproduce

1. follow HACS installation instructions
2. follow RTSP installation instructions
3. "add" integration
4. "add" hub
5. See error

### Screenshots & Logfiles

2023-06-14 15:45:16.201 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security async_step_user - None - {'_errors': {}, 'init_step': 'user', 'hass': <homeassistant.core.HomeAssistant object at 0x7f21820ccc90>, 'handler': 'eufy_security', 'flow_id': '4a4414295fdf589e1146c6668ee6e80d', 'context': {'source': 'user', 'show_advanced_options': True}, 'init_data': None}
2023-06-14 15:45:18.352 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security async_step_user - {'host': '127.0.0.1', 'port': 3000} - {'_errors': {}, 'init_step': 'user', 'hass': <homeassistant.core.HomeAssistant object at 0x7f21820ccc90>, 'handler': 'eufy_security', 'flow_id': '4a4414295fdf589e1146c6668ee6e80d', 'context': {'source': 'user', 'show_advanced_options': True}, 'init_data': None, 'cur_step': {'type': <FlowResultType.FORM: 'form'>, 'flow_id': '4a4414295fdf589e1146c6668ee6e80d', 'handler': 'eufy_security', 'step_id': 'user', 'data_schema': <Schema({'host': <class 'str'>, 'port': <class 'int'>}, extra=PREVENT_EXTRA, required=False) object at 0x7f211417f5d0>, 'errors': {}, 'description_placeholders': None, 'last_step': None}}
2023-06-14 15:45:18.357 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-06-14 15:45:18.358 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_close - executed
2023-06-14 15:45:18.362 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-06-14 15:45:18.362 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 17} - {'schemaVersion': 17}
2023-06-14 15:45:18.363 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.c594b42569a9434d88d0f4eb204d5895'}
2023-06-14 15:45:18.363 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.c594b42569a9434d88d0f4eb204d5895'}
2023-06-14 15:45:18.363 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.4.0', 'serverVersion': '1.3.0', 'minSchemaVersion': 0, 'maxSchemaVersion': 16}
2023-06-14 15:45:18.368 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'set_api_schema.c594b42569a9434d88d0f4eb204d5895', 'errorCode': 'schema_incompatible'}
2023-06-14 15:45:18.368 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.c594b42569a9434d88d0f4eb204d5895', 'errorCode': 'schema_incompatible'}

**Comment by bropat** [comment]
Wrong repo
