### ISSUE TITLE
[Bug]: Eufy Floodlight Pro 2 No alarm triggering

### ISSUE THREAD

**Issue by Flow76320** [bropat/hassio-eufy-security-ws#17]
### Add-on version

1.5.2

### Architecture

armv7

### HomeAssistant version

2023.6.2

### Operating System type

Linux

### Operating system version

HA OS 10.2

### Describe the bug

Hi, 

Thanks for maintaining this addon!
I forward the issue from https://github.com/fuatakgun/eufy_security/issues/752 which is still on-going.

Alarm can't be triggered for Eufy Floodlight pro 2. Here is the full error with camera ID replaced by XXXXXX:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 09:34:27 (1 occurrences)
Last logged: 09:34:27

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: {'type': 'result', 'success': False, 'messageId': 'device.trigger_alarm.XXXXXX', 'errorCode': 'device_not_supported'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 827, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/camera.py", line 241, in _async_alarm_trigger
    await self.product.trigger_alarm(duration)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 76, in trigger_alarm
    await self.api.trigger_alarm(self.product_type, self.serial_no, duration)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 202, in trigger_alarm
    await self._send_message_get_response(
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.trigger_alarm.XXXXXX', 'errorCode': 'device_not_supported'}
```

Let me know if I can help.

Thanks :) 

### To reproduce

1. Add the camera to Eufy account 
2. Go to the device entities
3. Click on the button "Trigger Alarm" (entity button.YOUR_CAMERA_trigger_alarm)

**Comment by bropat** [comment]
Wrong repo (read [here](https://github.com/bropat/hassio-eufy-security-ws#issues)).
